vich_uploader:
    db_driver: orm

    metadata:
      type: attribute

    mappings:
        uploads:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            # https://github.com/dustin10/VichUploaderBundle/blob/master/docs/usage.md#step-3-configure-the-lifecycle-events-optional-step
            # These are the default settings:
            # inject_on_load: false
            # delete_on_update: true
            # delete_on_remove: true
